#!/bin/bash -x
#Que.4
#Write a program that reads 5 Random 2 Digit values,then find their sum and the average

sum=0


for ((i=1; i<=5; i++))
do
            value=$((RANDOM%99+10))
            echo $value;
            sum=$((sum+value))

done
     echo "sum is $sum"
           avg=`echo $sum 5 |awk '{ print $1/$2 }'`
     echo "avg is $avg"

      

